services:
  - type: web
    name: claim-digital-assets
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: APP_BASE_URL
        value: https://claimdigitalassets.com
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PRICE_PRO
        sync: false
      - key: STRIPE_PRICE_ELITE
        sync: false
